In [ ]:
array([[11.40618132],
       [26.05449792],
       [38.09240055],
       [70.63460638],

In [23]:
O_effs[0:len(R_js)*len(axes)]

array([[25.07820468],
       [ 1.60469931],
       [37.35562378],
       [ 2.48145453],
       [70.06651682],
       [ 4.89755677]])

In [1]:
directory = '/Users/alaink/Software/StructuralGTEdits/StructuralGT/AgNWN_10um/Binarized'
#10um img is 41.2um long and 29.6 high (27.3 with scale bar removed)

import numpy as np
import pandas as pd
import itertools
import base

R_j_vals = (1,2,5)
axes = (0,1)
df = pd.DataFrame(columns=['Axis','R_j','O_eff'])

R_j_df = []
axes_df = []
O_eff_df = []
for i,Rjs_axes in enumerate(itertools.product(R_j_vals,axes)):
    print(i)
    R_j = Rjs_axes[0]
    axis = Rjs_axes[1]
    VC,G=base.voltage_distribution(directory, directory+'/skel.gsd', axis, [0,20], [480,800], crop=[0,500,0,500,0,500], _2d=True, R_j=R_j, rho_dim=1.62)
    L = np.load(directory+'/L.npy')
    Q = np.linalg.pinv(L)  
    O_eff = Q[-1,-1]+Q[-2,-2]-2*Q[-1,-2]
    
    R_j_df.append(R_j)
    axes_df.append(axis)
    O_eff_df.append(O_eff)
    
df['O_eff'] = O_eff_df
df['R_j'] = R_j_df
df['Axis'] = axes_df


#df.to_csv('AgNWN.csv')

0


OSError: [Errno 9] Bad file descriptor: '/Users/alaink/Software/StructuralGTEdits/StructuralGT/AgNWN_10um/Binarized/skel.gsd'

In [51]:
#df['Ratio']=np.hstack((df[df['Axis']==0]['O_eff'].values/df[df['Axis']==1]['O_eff'].values, df[df['Axis']==1]['O_eff'].values/df[df['Axis']==0]['O_eff'].values))
#df

Axis  R_j      O_eff      Ratio
0     0    1  25.078205  15.627977
1     1    1   1.604699  15.053922
2     0    2  37.355624  14.306423
3     1    2   2.481455   0.063988
4     0    5  70.066517   0.066428
5     1    5   4.897557   0.069899

In [163]:
#Isotropic analysis

#Only need to run these once
#base.ExpProcess('AgNWN_iso')
#base.stack_to_gsd('AgNWN_iso/Binarized','skel.gsd')


directory = '/Users/alaink/Software/StructuralGTEdits/StructuralGT/AgNWN_iso/Binarized'
df_iso = pd.DataFrame(columns=['Axis','R_j','O_eff'])
R_j_df = []
axes_df = []
O_eff_df = []
R_j_vals = (2,3)
axes = (0,1)
for i,Rjs_axes in enumerate(itertools.product(R_j_vals,axes)):
    print(i)
    R_j = Rjs_axes[0]
    axis = Rjs_axes[1]
    VC,G=base.voltage_distribution(directory, 'AgNWN_iso/skel.gsd', axis, [0,20], [1580,1600], crop=[0,1600,0,1600,0,1600], _2d=True, R_j=R_j, rho_dim=1.62)
    L = np.load(directory+'/L.npy')
    Q = np.linalg.pinv(L)  
    O_eff = Q[-1,-1]+Q[-2,-2]-2*Q[-1,-2]
    
    R_j_df.append(R_j)
    axes_df.append(axis)
    O_eff_df.append(O_eff)
    
df_iso['O_eff'] = O_eff_df
df_iso['R_j'] = R_j_df
df_iso['Axis'] = axes_df


0
first pos  [[   0    0  111]
 [   0    0  164]
 [   0    0  165]
 ...
 [   0 1763 1934]
 [   0 1763 2039]
 [   0 1763 2040]]
pre crop pos  [[   0    0  111]
 [   0    0  164]
 [   0    0  165]
 ...
 [   0 1763 1934]
 [   0 1763 2039]
 [   0 1763 2040]]
pre shift pos  [[   0    0  111]
 [   0    0  164]
 [   0    0  165]
 ...
 [   0 1600 1571]
 [   0 1600 1572]
 [   0 1600 1573]]
final pos for  AgNWN_iso/skel.gsd  is  [[   0  111]
 [   0  164]
 [   0  165]
 ...
 [1600 1571]
 [1600 1572]
 [1600 1573]]
(1601, 1601)
gsd_to_G canvas has shape  (1601, 1601)
[[  0 111]]
(0, 234, array([[  0, 111],
       [  1, 111],
       [  2, 110],
       [  3, 110],
       [  4, 110],
       [  5, 110],
       [  6, 110],
       [  7, 110],
       [  8, 110],
       [  9, 110],
       [ 10, 109],
       [ 11, 109],
       [ 12, 109],
       [ 13, 109],
       [ 14, 109],
       [ 15, 109],
       [ 16, 109],
       [ 17, 109],
       [ 18, 108],
       [ 19, 108],
       [ 20, 108],
       [ 21, 108]], 

IndexError: too many indices for array: array is 1-dimensional, but 3 were indexed

In [68]:
df_iso

Axis  R_j      O_eff
0     0    2  64.259411
1     1    2  25.204991
2     0    3  87.475173
3     1    3  34.217192

In [4]:
crop = [-177,177,-177,177,-177,177]
theta = np.pi/4
rot_mat = R.from_quat([np.cos(theta/2),0,0,np.sin(theta/2)]).as_matrix()
rot_mat=90
base.stack_to_gsd('AgNWN_10um/Binarized', 'test.gsd', crop=crop, rotate=rot_mat)

IndexError: index 1 is out of bounds for axis 0 with size 1

In [4]:
#Rotation matrix test
directory = '/Users/alaink/Software/StructuralGTEdits/StructuralGT/AgNWN_10um'
import gsd.hoomd
import matplotlib.pyplot as plt
from numpy import logical_and as a
from scipy.spatial.transform import Rotation as R
from PIL import Image
from skimage.morphology import binary_closing, ball, diamond, square, disk
#Crop to outer square
outer_crop = 1000
crop = [0,outer_crop,0,outer_crop,0,outer_crop]
frame = gsd.hoomd.open(name=directory+'/skel.gsd', mode='rb')[0]
p = base.shift(frame.particles.position.astype(int)).T
positions = p.T[a(a(a(a(a(p[0]>=crop[0],p[0]<=crop[1]),p[1]>=crop[2]),p[1]<=crop[3]),p[2]>=crop[4]),p[2]<=crop[5])]

#Centre on origin, rotate and recrop to the inner square
positions = base.oshift(positions)
theta = 0#np.pi/4
rot_mat = R.from_quat([np.cos(theta/2),0,0,np.sin(theta/2)]).as_matrix()
p = np.matmul(positions,rot_mat).T.astype(int)
inner_crop = int(outer_crop/(2*2**0.5))
crop = [0,inner_crop,0,inner_crop,0,inner_crop]
positions = base.shift(positions)
positions = p.T[a(a(a(a(a(p[0]>=crop[0],p[0]<=crop[1]),p[1]>=crop[2]),p[1]<=crop[3]),p[2]>=crop[4]),p[2]<=crop[5])]


#Fill rotated skel to account for edges broken during the rotation
dims = np.asarray(list(max(positions.T[i])+1 for i in (0,1,2)))
canvas = np.zeros(dims)
canvas[positions.T[0], positions.T[1], positions.T[2]] = 1
img_bin = canvas
img_bin = binary_closing(img_bin, selem=ball(3))
positions = np.asarray(np.where(img_bin != 0)).T


#Write rotated positions to new temporary gsd
s = gsd.hoomd.Snapshot()
s.particles.N = len(positions)
s.particles.types = ['A']
s.particles.typeid = ['0']*s.particles.N
s.particles.position = positions
print(positions)



with gsd.hoomd.open(name=directory+'/Rotations/rot_skel.gsd', mode='wb') as f:
    f.append(s)

#Need to reassign weights from a temporary rotated binary image
#First write the temporary image
with Image.open(directory+'/Binarized/slice0.tiff') as im:
    #img_crop=im.crop((0,0,outer_crop, outer_crop)) #Crop to outer square
    img_rot=im.rotate(theta*180/np.pi) #Rotate
    
    #Calculate inner square positions and crop to it
    bottom = (2*outer_crop*2**0.5 - outer_crop)/(4*2**0.5)
    top = outer_crop - bottom
    img_crop = img_rot.crop((591,686,945,332))
    img_crop.save(directory+'/Rotations/slice0.tiff') 

VC,G=base.voltage_distribution(directory+'/Rotations', directory+'/Rotations/rot_skel.gsd', 0, [0,20], [inner_crop-20,inner_crop], crop=crop, _2d=True, R_j=R_j, rho_dim=1.62)
L = np.load(directory+'/Rotations/L.npy')
Q = np.linalg.pinv(L)
O_eff = Q[-1,-1]+Q[-2,-2]-2*Q[-1,-2]

fig = plt.figure()
ax = fig.add_subplot(111)

plt.scatter(positions.T[1],positions.T[2],s=0.005)

ax.set_aspect('equal', adjustable='box')

[[  0   0   4]
 [  0   0   5]
 [  0   0   6]
 ...
 [  0 353 351]
 [  0 353 352]
 [  0 353 353]]


ZeroDivisionError: integer division or modulo by zero

In [7]:
crop = [0,20,0,20,0,20]
positions = np.array([[0,5,10],[0,100,200],[0,100,5]])
from numpy import logical_and as a
p = positions.T
positions = p.T[a(a(a(a(a(p[0]>=crop[0],p[0]<=crop[1]),p[1]>=crop[2]),p[1]<=crop[3]),p[2]>=crop[4]),p[2]<=crop[5])]
positions

array([[ 0,  5, 10]])